version: '3.8'
services:
  iris:
    build:
      context: .
      dockerfile: IrisDockerfile
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 51773:1972
      - 52773:52773
      - 53773
    volumes:
    # - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
    networks:
      - iris_network
      - db_network
      - web_network
  appmsw:
    container_name: appmsw
    restart: always
    build: .
    networks:
      - db_network
      - web_network
      - iris_network
  nginxs:
    container_name: nginxs
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appmsw
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  iris_network:
    driver: bridge
 