;do $System.OBJ.LoadDir("/opt/irisapp/src","ck",,1)

zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")
; zpm "load https://github.com/SergeyMi37/zapm.git"
; zapm "newdb https://github.com/SergeyMi37/DevBox.git"
; zapm "newdb https://github.com/intersystems-community/webterminal"
 
zn "USER"
zpm "load https://github.com/SergeyMi37/apptools-admin.git" 
zpm "load /opt/irisapp/ -v":1

;zn "%SYS"
;zpm "load https://github.com/SergeyMi37/isc-passwordless.git"
halt
