# Generated by Django 4.2.5 on 2023-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='param',
            old_name='code',
            new_name='json',
        ),
        migrations.RemoveField(
            model_name='param',
            name='paropt',
        ),
        migrations.AddField(
            model_name='param',
            name='option',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='param',
            name='category',
            field=models.CharField(choices=[('sys', 'System Parameter'), ('app', 'Application Parameter'), ('sidemenu', 'Side Menu'), ('topmenu', 'Top Menu'), ('prj', 'Project')], default='app', max_length=30),
        ),
    ]
