# Generated by Django 4.2.5 on 2023-10-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmsw', '0002_rename_code_param_json_remove_param_paropt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='category',
            field=models.CharField(choices=[('systems', 'Systems Parameters Integrations'), ('app', 'Application Parameters'), ('sidemenu', 'Side Menu'), ('topmenu', 'Top Menu'), ('prj', 'Project')], default='app', max_length=30),
        ),
    ]
